version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "08:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: rc-util
    versions:
    - 5.10.1
    - 5.11.1
    - 5.12.0
    - 5.7.0
    - 5.8.0
    - 5.8.1
    - 5.9.1
    - 5.9.4
    - 5.9.5
    - 5.9.8
    - 5.9.9
  - dependency-name: core-js
    versions:
    - 3.10.0
    - 3.10.1
    - 3.10.2
    - 3.11.0
    - 3.8.3
    - 3.9.0
    - 3.9.1
  - dependency-name: react
    versions:
    - 17.0.1
  - dependency-name: jquery
    versions:
    - 3.5.1
